include:
  - component: $CI_SERVER_FQDN/nci-gdc/platform-engineering/generate-version/generate_version@0.4.2
    inputs:
      stage: tag
  - component: $CI_SERVER_FQDN/nci-gdc/gitlab-templates/pre-commit@feat/components
  - component: $CI_SERVER_FQDN/nci-gdc/gitlab-templates/tox@feat/components
    inputs:
      python_version: "3.12"
      use_uv: false
      image_version: "3.6.0"
  - component: $CI_SERVER_FQDN/nci-gdc/gitlab-templates/docker-build@feat/components
  - component: $CI_SERVER_FQDN/nci-gdc/gitlab-templates/docker-release@feat/components
  - component: $CI_SERVER_FQDN/nci-gdc/gitlab-templates/docker-release-latest@feat/components

stages:
  - test
  - build
  - release
  - tag
