---
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml

variables:
  BUILD_PY_VERSION: python3.12
  RELEASE_PY_VERSION: python3.12

.parallel:
  parallel:
    matrix:
      - BUILD_PY_VERSION: [python3.12]
