include:
  - component: $CI_SERVER_FQDN/nci-gdc/platform-engineering/generate-version/generate_version@0.4.2
    inputs:
      stage: tag
  - component: $CI_SERVER_FQDN/nci-gdc/gitlab-templates/workflow@1.6.1
  - component: $CI_SERVER_FQDN/nci-gdc/gitlab-templates/pre-commit@1.6.1
  - component: $CI_SERVER_FQDN/nci-gdc/gitlab-templates/tox@1.6.1
    inputs:
      python_version: "3.12"
      image_version: "4.4.1"
  - component: $CI_SERVER_FQDN/nci-gdc/gitlab-templates/docker-build@1.6.1
    inputs:
      image_version: "4"
  - component: $CI_SERVER_FQDN/nci-gdc/gitlab-templates/docker-release@1.6.1
  - component: $CI_SERVER_FQDN/nci-gdc/gitlab-templates/docker-release-latest@1.6.1

stages:
  - test
  - build
  - release
  - tag

tox:
  image: docker.osdc.io/ncigdc/amzn2023-builder:4.4.1
