---
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml

variables:
  BUILD_PY_VERSION: python3.12
  RELEASE_PY_VERSION: python3.12
  PIP_INDEX_URL: https://nexus.osdc.io/repository/pypi-all/simple

.parallel:
  parallel:
    matrix:
      - BUILD_PY_VERSION: [python3.12]
