language: python

python:
  - "3.5.2"

before_install:
  - pip freeze

install:
  - yes | python setup.py install
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt


before_script:
  - pip freeze

script: "python -m pytest tests/"
