language: python

python:
  - "2.7.15"

before_install:
  - pip freeze

install:
  - pip install -r requirements.txt
  - python setup.py install

before_script:
  - pip freeze

script: "python -m pytest tests/"
